version: "3"

includes:
  deps: "taskfiles/deps.yaml"
  utils: "tools/yscope-dev-utils/exports/taskfiles/utils/utils.yaml"

vars:
  G_BUILD_DIR: "{{.ROOT_DIR}}/build"
  G_DEPS_DIR: "{{.G_BUILD_DIR}}/deps"
  G_DIST_DIR: "{{.ROOT_DIR}}/dist"
  G_EMSDK_DIR: "{{.G_BUILD_DIR}}/emsdk"
  G_ZSTD_WASM_BUILD_DIR: "{{.G_BUILD_DIR}}/zstd-wasm"

  G_ZSTD_WASM_ENV_NAMES: ["node", "worker"]
  G_ZSTD_WASM_TARGET_PREFIX: "zstd-wasm-"

  # These should be kept in-sync with their usage in CMakeLists.txt
  G_DEPS_CMAKE_SETTINGS_DIR: "{{.G_DEPS_DIR}}/cmake-settings"
  G_DEPS_CMAKE_SETTINGS_FILE: "{{.G_DEPS_CMAKE_SETTINGS_DIR}}/settings.cmake"

  G_DEPS_CHECKSUM: "{{.G_BUILD_DIR}}/deps.md5"
  G_ZSTD_WASM_CHECKSUM: "{{.G_BUILD_DIR}}/zstd-wasm.md5"

tasks:
  default:
    deps: ["package"]

  clean:
    cmds:
      - task: "clean-zstd-wasm"
      - task: "deps:clean"
      - "rm -rf '{{.G_BUILD_DIR}}'"

  clean-zstd-wasm:
    cmds:
      - "rm -rf '{{.G_ZSTD_WASM_BUILD_DIR}}'"

  package:
    vars:
      CHECKSUM_FILE: "{{.G_BUILD_DIR}}/{{.TASK}}.md5"
      OUTPUT_DIR: "{{.G_DIST_DIR}}"
    sources:
      - "{{.G_ZSTD_WASM_CHECKSUM}}"
      - "{{.TASKFILE}}"
      - "src/**/*"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.json"
    generates: ["{{.CHECKSUM_FILE}}"]
    deps:
      - "zstd-wasm"
      - task: "utils:checksum:validate"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.OUTPUT_DIR}}"]
    cmds:
      - "rm -rf {{.OUTPUT_DIR}}"
      - "mkdir -p {{.OUTPUT_DIR}}"
      - for:
          var: "G_ZSTD_WASM_ENV_NAMES"
        cmd: >-
          rsync -a
          {{.G_ZSTD_WASM_BUILD_DIR}}/{{.G_ZSTD_WASM_TARGET_PREFIX}}{{.ITEM}}.{d.ts,js,wasm}
          "{{.OUTPUT_DIR}}/"
      - "npm run build:ts"
      - "npm pack"
      # This command must be last
      - task: "utils:checksum:compute"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.OUTPUT_DIR}}"]

  zstd-wasm:
    vars:
      CHECKSUM_FILE: "{{.G_ZSTD_WASM_CHECKSUM}}"
      OUTPUT_DIR: "{{.G_ZSTD_WASM_BUILD_DIR}}"
    sources:
      - "{{.G_ZSTD_WASM_BUILD_DIR}}/CMakeCache.txt"
      - "{{.TASKFILE}}"
      - "CMakeLists.txt"
      - "src/**/*"
    generates: ["{{.CHECKSUM_FILE}}"]
    deps:
      - "config-cmake-project"
      - task: "utils:checksum:validate"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.OUTPUT_DIR}}"]
    cmds:
      - >-
        cmake
        --build '{{.OUTPUT_DIR}}'
        --parallel
        --target {{range .G_ZSTD_WASM_ENV_NAMES}}"{{$.G_ZSTD_WASM_TARGET_PREFIX}}{{.}}" {{end}}
      # This command must be last
      - task: "utils:checksum:compute"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          INCLUDE_PATTERNS: ["{{.OUTPUT_DIR}}"]

  config-cmake-project:
    internal: true
    sources:
      - "{{.G_DEPS_CHECKSUM}}"
      - "{{.TASKFILE}}"
      - "CMakeLists.txt"
    generates:
      - "{{.G_ZSTD_WASM_BUILD_DIR}}/CMakeCache.txt"
    deps:
      - "deps"
    cmd: |-
      cmake \
      -DZSTD_WASM_SUPPORTED_ENVIRONMENTS="{{.G_ZSTD_WASM_ENV_NAMES | join ";"}}" \
      -DCMAKE_TOOLCHAIN_FILE="{{.G_EMSDK_DIR}}/upstream/emscripten/cmake/Modules/Platform/\
      Emscripten.cmake" \
      -S "{{.ROOT_DIR}}" \
      -B "{{.G_ZSTD_WASM_BUILD_DIR}}"

  init:
    internal: true
    silent: true
    run: "once"
    cmds: ["mkdir -p '{{.G_BUILD_DIR}}'"]
