name: "publish-to-npm"

on:
  release:
    types: ["created"]
  workflow_dispatch:

env:
  G_ZSTD_FFI_JS_DIST_ARTIFACT_NAME: "zstd-ffi-js-dist-${{github.sha}}"

permissions: {}

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8"
        with:
          submodules: "recursive"

      - name: "Install task"
        run: "npm install --global @go-task/cli@3.44.0"

      - run: "task"

      - name: "Upload build artifacts"
        uses: "actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02"
        with:
          name: "${{env.G_ZSTD_FFI_JS_DIST_ARTIFACT_NAME}}"
          path: "dist/"
          if-no-files-found: "error"
          retention-days: 1

  publish-to-npm:
    needs: ["build"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8"
      - uses: "actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0"
        with:
          name: "${{env.G_ZSTD_FFI_JS_DIST_ARTIFACT_NAME}}"
          path: "dist/"

      - uses: "actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020"
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org/"

      - run: "npm publish"
        env:
          NODE_AUTH_TOKEN: "${{secrets.NPM_TOKEN}}"